apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app-dev
  template:
    metadata:
      labels:
        app: hello-app-dev
        visualize: "true"
    spec:
      containers:
      - name: hello-app-dev-pod
        image: mtararujs/hello-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: hello-app-dev-service
spec:
  selector:
    app: hello-app-dev
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 8080
  type: LoadBalancer